# На каком порту стартует приложение
server:
    port: 8081

# Задать своего пользователя в In-Memory аутентификации
spring:
    security:
        user:
            name: alex
            password: 123
