# На каком порту стартует приложение
server:
    port: 8085

# Настройки логирования
logging:
    level:
        com.spring.example5: debug
    file:
        name: example5_jdbc_auth/logs/app_debug.log

# Настройки БД
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:example5;MODE=PostgreSQL
        username: sa
        password:
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console # web-консоль
            settings:
                web-allow-others: false
