# На каком порту стартует приложение
server:
    port: 8084

# Настройки логирования
logging:
    level:
        com.spring.example4: debug
    file:
        name: example4_custom_authentication_provider/logs/app_debug.log

# Настройки БД
spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:example4;MODE=PostgreSQL
        username: sa
        password:
    jpa:
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true # web-консоль по адресу: /h2-console
            settings:
                web-allow-others: false
